# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traffic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Traffic(object):
    def setupUi(self, Traffic):
        Traffic.setObjectName("Traffic")
        Traffic.resize(1575, 881)
        self.frm_video_main = QtWidgets.QFrame(Traffic)
        self.frm_video_main.setGeometry(QtCore.QRect(240, 180, 720, 540))
        self.frm_video_main.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_video_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_video_main.setLineWidth(1)
        self.frm_video_main.setObjectName("frm_video_main")
        self.lbl_video_main = WLabel(self.frm_video_main)
        self.lbl_video_main.setGeometry(QtCore.QRect(0, 0, 720, 540))
        self.lbl_video_main.setMidLineWidth(1)
        self.lbl_video_main.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_main.setObjectName("lbl_video_main")
        self.frame_2 = QtWidgets.QFrame(Traffic)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.lbl_video_4 = WLabel(self.frame_2)
        self.lbl_video_4.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_4.setObjectName("lbl_video_4")
        self.frame_3 = QtWidgets.QFrame(Traffic)
        self.frame_3.setGeometry(QtCore.QRect(240, 0, 240, 180))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.lbl_video_5 = WLabel(self.frame_3)
        self.lbl_video_5.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_5.setObjectName("lbl_video_5")
        self.frame_4 = QtWidgets.QFrame(Traffic)
        self.frame_4.setGeometry(QtCore.QRect(480, 0, 240, 180))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.lbl_video_6 = WLabel(self.frame_4)
        self.lbl_video_6.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_6.setObjectName("lbl_video_6")
        self.frame_5 = QtWidgets.QFrame(Traffic)
        self.frame_5.setGeometry(QtCore.QRect(720, 0, 240, 180))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.lbl_video_7 = WLabel(self.frame_5)
        self.lbl_video_7.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_7.setObjectName("lbl_video_7")
        self.frame_6 = QtWidgets.QFrame(Traffic)
        self.frame_6.setGeometry(QtCore.QRect(0, 180, 240, 180))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.lbl_video_3 = WLabel(self.frame_6)
        self.lbl_video_3.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_3.setObjectName("lbl_video_3")
        self.frame_7 = QtWidgets.QFrame(Traffic)
        self.frame_7.setGeometry(QtCore.QRect(0, 360, 240, 180))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setObjectName("frame_7")
        self.lbl_video_2 = WLabel(self.frame_7)
        self.lbl_video_2.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_2.setObjectName("lbl_video_2")
        self.frame_8 = QtWidgets.QFrame(Traffic)
        self.frame_8.setGeometry(QtCore.QRect(0, 540, 240, 180))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_8.setObjectName("frame_8")
        self.lbl_video_1 = WLabel(self.frame_8)
        self.lbl_video_1.setGeometry(QtCore.QRect(0, 0, 240, 180))
        self.lbl_video_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video_1.setObjectName("lbl_video_1")
        self.frame_9 = QtWidgets.QFrame(Traffic)
        self.frame_9.setGeometry(QtCore.QRect(0, 725, 960, 150))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.btn_gray = QtWidgets.QRadioButton(self.frame_9)
        self.btn_gray.setGeometry(QtCore.QRect(180, 60, 110, 19))
        self.btn_gray.setObjectName("btn_gray")
        self.bgr_video_handle = QtWidgets.QButtonGroup(Traffic)
        self.bgr_video_handle.setObjectName("bgr_video_handle")
        self.bgr_video_handle.addButton(self.btn_gray,101)
        self.btn_clear = QtWidgets.QRadioButton(self.frame_9)
        self.btn_clear.setGeometry(QtCore.QRect(310, 60, 110, 19))
        self.btn_clear.setObjectName("btn_clear")
        self.bgr_video_handle.addButton(self.btn_clear,102)
        self.btn_contour = QtWidgets.QRadioButton(self.frame_9)
        self.btn_contour.setGeometry(QtCore.QRect(440, 60, 110, 19))
        self.btn_contour.setObjectName("btn_contour")
        self.bgr_video_handle.addButton(self.btn_contour,103)
        self.sld_brightness = QtWidgets.QSlider(self.frame_9)
        self.sld_brightness.setGeometry(QtCore.QRect(670, 60, 271, 22))
        self.sld_brightness.setMaximum(255)
        self.sld_brightness.setSingleStep(5)
        self.sld_brightness.setProperty("value", 128)
        self.sld_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.sld_brightness.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.sld_brightness.setTickInterval(20)
        self.sld_brightness.setObjectName("sld_brightness")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setGeometry(QtCore.QRect(580, 60, 68, 21))
        self.label_9.setObjectName("label_9")
        self.btn_src = QtWidgets.QRadioButton(self.frame_9)
        self.btn_src.setGeometry(QtCore.QRect(40, 60, 110, 19))
        self.btn_src.setChecked(True)
        self.btn_src.setObjectName("btn_src")
        self.bgr_video_handle.addButton(self.btn_src)
        self.frm_info = QtWidgets.QFrame(Traffic)
        self.frm_info.setGeometry(QtCore.QRect(970, 0, 600, 876))
        self.frm_info.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_info.setLineWidth(2)
        self.frm_info.setObjectName("frm_info")
        self.frame_11 = QtWidgets.QFrame(self.frm_info)
        self.frame_11.setGeometry(QtCore.QRect(5, 5, 588, 340))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.wdt_map = QtWebEngineWidgets.QWebEngineView(self.frame_11)
        self.wdt_map.setGeometry(QtCore.QRect(5, 5, 578, 330))
        self.wdt_map.setObjectName("wdt_map")
        self.frame_12 = QtWidgets.QFrame(self.frm_info)
        self.frame_12.setGeometry(QtCore.QRect(5, 390, 588, 200))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.lsv_warning = QtWidgets.QListView(self.frame_12)
        self.lsv_warning.setGeometry(QtCore.QRect(5, 5, 580, 190))
        self.lsv_warning.setObjectName("lsv_warning")
        self.label_11 = QtWidgets.QLabel(self.frm_info)
        self.label_11.setGeometry(QtCore.QRect(220, 350, 131, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.frame_13 = QtWidgets.QFrame(self.frm_info)
        self.frame_13.setGeometry(QtCore.QRect(5, 640, 588, 230))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.tbv_log = QtWidgets.QTableView(self.frame_13)
        self.tbv_log.setGeometry(QtCore.QRect(5, 5, 580, 220))
        self.tbv_log.setObjectName("tbv_log")
        self.label_12 = QtWidgets.QLabel(self.frm_info)
        self.label_12.setGeometry(QtCore.QRect(220, 600, 131, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Traffic)
        self.bgr_video_handle.buttonClicked['int'].connect(Traffic.handle_video)
        self.sld_brightness.valueChanged['int'].connect(Traffic.modify_bright)
        QtCore.QMetaObject.connectSlotsByName(Traffic)

    def retranslateUi(self, Traffic):
        _translate = QtCore.QCoreApplication.translate
        Traffic.setWindowTitle(_translate("Traffic", "交通违规监控系统"))
        self.lbl_video_main.setText(_translate("Traffic", "<font color=red size=6><b>街口监控视频主显示区</b></font>"))
        self.lbl_video_4.setText(_translate("Traffic", "街口-4"))
        self.lbl_video_5.setText(_translate("Traffic", "接口-5"))
        self.lbl_video_6.setText(_translate("Traffic", "接口-6"))
        self.lbl_video_7.setText(_translate("Traffic", "接口-7"))
        self.lbl_video_3.setText(_translate("Traffic", "街口-3"))
        self.lbl_video_2.setText(_translate("Traffic", "街口-2"))
        self.lbl_video_1.setText(_translate("Traffic", "街口-1"))
        self.btn_gray.setText(_translate("Traffic", "黑白视频"))
        self.btn_clear.setText(_translate("Traffic", "清晰度"))
        self.btn_contour.setText(_translate("Traffic", "线条图"))
        self.label_9.setText(_translate("Traffic", "亮度："))
        self.btn_src.setText(_translate("Traffic", "原始视频"))
        self.label_11.setText(_translate("Traffic", "<font color=\"blue\" size=4><strong>违规信息报警</strong></font>"))
        self.label_12.setText(_translate("Traffic", "<font color=\"blue\" size=4><strong>监控日志信息</strong></font>"))

from PyQt5 import QtWebEngineWidgets
from trafficapp.uis.wcomponents import WLabel